### ISSUE TITLE
建议在线用户列表users换用对象保存

### ISSUE THREAD

**Issue by abbshr** [nswbmw/N-chat#1]
如果users用数组的话，每当一个用户下线时，如果此时恰巧有用户上线，那么users的长度就会发生变化，因此待删除的用户在数组中的位置也会发生改变，这样容易误删用户。

改用对象保存：

`var users = {};`

```
function User(name) {
    this.name = name;
}
```

上线时：

`users[data.name] = new User(data.name);`

下线时：

`delete user[socket.name]`

**Comment by nswbmw** [comment]
谢谢~说得很对，已修改
